### ISSUE TITLE
Support for GCS

### ISSUE THREAD

**Issue by edbizarro** [ets/tap-spreadsheets-anywhere#1]
Any plans to support GCS protocol?

Thanks!

**Comment by ets** [comment]
The ability to read objects is there via smart_open. Just need the logic added to list files in a directory and handle filtering contents on last_modified.

**Comment by ets** [comment]
@edbizarro latest commit on master adds GCS support with the path prefix "gs://" using sample code from Google's docs, but not tested.  Caveat Emptor!
