### ISSUE TITLE
Tap not adding metadata to the records

### ISSUE THREAD

**Issue by fakhavan** [ets/tap-spreadsheets-anywhere#13]
I got an error using this tap to load data (have faced the issue using both [PostgreSQL](https://meltano.com/plugins/loaders/postgres.html) and [Snowflake](https://meltano.com/plugins/loaders/snowflake.html) loaders). Basically, the table is created in those databases assuming the metadata fields (eg: `_smart_source_bucket`) can not be Null but actually they are not passed as part of the record to the database, so the database fails cause it assume those columns can't be null.

@DouweM Took a look and discovered the following:

> it looks like https://github.com/ets/tap-spreadsheets-anywhere/blob/cc03db106f4fe81fef7696c0743022af5e511a65/tap_spreadsheets_anywhere/file_utils.py#L38 inserts that metadata into record , just like the metadata schema is inserted into the record schema here: 
> https://github.com/ets/tap-spreadsheets-anywhere/blob/c92a153a85551b47e715e9348b02bca79d90bca0/tap_spreadsheets_anywhere/__init__.py#L64
> 
> But, that's not actually what transformer.transform  does with its metadata argument: 
> https://github.com/singer-io/singer-python/blob/2f618c6194f154be7ba37f288d456f6abd4d78ec/singer/transform.py#L148
> 
> which is only used to find out if a specific column should be selected or not:
> https://github.com/singer-io/singer-python/blob/2f618c6194f154be7ba37f288d456f6abd4d78ec/singer/transform.py#L128
> 
> So the tap is currently claiming that each row will have non-null _smart_<etc> fields, but they never actually end up in the RECORD messages
> 
> This bug was introduced by https://github.com/ets/tap-spreadsheets-anywhere/commit/a59fdfd63c86cefb6abfb767f7d1cb216be65c6c 
> 
> To fix, we should merge metadata into record again, and the actual stream-specific metadata that transform.transform wants to determine which fields to include should be coming from the catalog here: https://github.com/ets/tap-spreadsheets-anywhere/blob/2df74eb81ce8eee555b7a01de4813c8f48de4e2b/tap_spreadsheets_anywhere/__init__.py#L94 and passed to write_file here: https://github.com/ets/tap-spreadsheets-anywhere/blob/2df74eb81ce8eee555b7a01de4813c8f48de4e2b/tap_spreadsheets_anywhere/__init__.py#L114

**Comment by DouweM** [comment]
@CoopTang You may want to check this out since this bug was accidentally introduced by your https://github.com/ets/tap-spreadsheets-anywhere/pull/7!

**Comment by ets** [comment]
Backed out change that introduced transformer.transform to restore smart columns.  PR to use it appropriately welcomed!
