### ISSUE TITLE
Azure support

### ISSUE THREAD

**Issue by radbrt** [ets/tap-spreadsheets-anywhere#31]
I'm jumping into this tap on short notice, but I needed to add Azure Blob support and made a bare-bones implementation here: https://github.com/radbrt/tap-spreadsheets-anywhere/tree/azure

Before making a PR, I'd like to discuss some of the issues/choices involved here.

First off, I'm reading files based on the smart_open example for reading Azure, where we depend on a storage account connection string with a particular formatting. For better or worse, Azure has a myriad of ways to connect to blobs, and this implementation does not support access methods such as Managed Identity (granted, azure hardly supports that either). The particular formatting, although found in the Azure Portal, may also be a little intuitive for users, compared to other formats. This formatting issue can probably be fixed through documentation though.

The way the credential is stored is also grabbed from the smart_open example - I simply assume an env variable is present (https://github.com/radbrt/tap-spreadsheets-anywhere/blob/53d8429657be1cca363a7c2a2a23eb0f7d4a97bd/tap_spreadsheets_anywhere/file_utils.py#L253). In Meltano, this works well by adding it to the .env file. But if anyone wants to read from mulitple azure storage accounts, this will be hard to configure. There are a few possible ways around this, with different tradeoffs.

Reading files from azure requires an additional parameter smart_open's `open` function, and I if-elsed that one very crudely. Any ideas for cleaner implementations are welcome: https://github.com/radbrt/tap-spreadsheets-anywhere/blob/53d8429657be1cca363a7c2a2a23eb0f7d4a97bd/tap_spreadsheets_anywhere/format_handler.py#L22

Lastly, I'm simply importing the azure.storage.blob at the top, while I see some libraries are imported in try-blocks only if the specified protocol requires it.

**Comment by pnadolny13** [comment]
cc @menzenski since it sounds like they might be taking over some of the maintainer duties based on https://github.com/ets/tap-spreadsheets-anywhere/pull/28#issuecomment-1358614162 😄

**Comment by menzenski** [comment]
Thanks @pnadolny13 - @ets has indeed made me a collaborator on this repository although I haven't really taken any actions yet in that capacity.

I'll preface this comment with a caveat that I don't personally have any Azure experience. My own cloud experience is really AWS-only.

>  In Meltano, this works well by adding it to the .env file. But if anyone wants to read from mulitple azure storage accounts, this will be hard to configure. 

My understanding is that this is something that's generally true of Meltano plugins - separating environment variables in this way isn't possible.  (I don't believe I could do that with AWS S3 either).

Is there a need to connect to mulitple azure storage accounts in the same invocation of the same tap? Or could you use [plugin inheritance](https://docs.meltano.com/guide/plugin-management#plugin-inheritance) to run the tap once for each storage account, providing different environment variables to each run?

**Comment by radbrt** [comment]
@menzenski plugin inheritance is one of the solutions I thought of, so we could add the connection string to the config and treat it like a normal password. I don't have any objections to that solution.

**Comment by menzenski** [comment]
Regarding your other question about the additional parameter:

I think my personal preference would be for something like this:
```python
def get_streamreader(uri, universal_newlines=True,newline='',open_mode='r'):
    transport_params = None

    if uri.startswith('azure://'):
        connect_str = os.environ['AZURE_STORAGE_CONNECTION_STRING']
        transport_params = {
            'client': BlobServiceClient.from_connection_string(connect_str),
        }

    streamreader = smart_open.open(uri, open_mode, newline=newline, errors='surrogateescape', transport_params=transport_params)
    if not universal_newlines and isinstance(streamreader, StreamReader):
        return monkey_patch_streamreader(streamreader)
    return streamreader
```

This would keep the single reference to `smart_open.open` and would also keep the monkeypatching for azure (though to be honest I don't know if that's required).

**Comment by z3z1ma** [comment]
I would do this @radbrt 

```python

kwarg_dispatch = {
    "azure": {
        "transport_params": {
            "client": BlobServiceClient.from_connection_string(
                os.environ['AZURE_STORAGE_CONNECTION_STRING'],
            )
        }
    },
    "gcs": {
        "transport_params": {
            "client": storage.Client.from_service_account_json(
                os.environ['GOOGLE_APPLICATION_CREDENTIALS'],
                # We can add more nuanced transport params here
            )
        }
    },
   # Adding support for more is intuitive...
}

SCHEME_SEP = "://"

if SCHEME_SEP in uri:
    kwargs = kwarg_dispatch.get(uri.split(SCHEME_SEP, 1)[0], {})
    
streamreader = smart_open.open(uri, open_mode, newline=newline, errors='surrogateescape', **kwargs)
if not universal_newlines and isinstance(streamreader, StreamReader):
    return monkey_patch_streamreader(streamreader)
return streamreader
```

**Comment by z3z1ma** [comment]
Or as an FP 1-liner if you go full-tilt 😆 same thing.

```python
def get_streamreader(uri: str, universal_newlines: bool = True, newline: str = "", open_mode: str = "r"):
  return (lambda rdr: rdr if not universal_newlines and isinstance(rdr, StreamReader) 
                          else monkey_patch_streamreader(rdr))(
    smart_open.open(uri, open_mode, newline=newline, errors="surrogateescape", **{
        "azure": lambda: {
            "transport_params": {
                "client": BlobServiceClient.from_connection_string(
                    os.environ["AZURE_STORAGE_CONNECTION_STRING"],
                )
            }
        },
        "gcs": lambda: {
            "transport_params": {
                "client": storage.Client.from_service_account_json(
                    os.environ["GOOGLE_APPLICATION_CREDENTIALS"],
                    # We can add more nuanced transport params here
                )
            }
        },
       # Adding support for more is intuitive...
    }.get(uri.split("://", 1)[0], lambda: {})())
  )
```

**Comment by menzenski** [comment]
@radbrt I'd encourage you to go ahead and open a PR for this.

**Comment by radbrt** [comment]
@menzenski I absolutely plan to, there were a lot of good ideas here. Will probably have time this weekend.
