### ISSUE TITLE
Tap silently skipping some config items?

### ISSUE THREAD

**Issue by andrewcstewart** [ets/tap-spreadsheets-anywhere#5]
I've noticed that some http/s paths seem to get silently skipped by the tap.  

example: https://dataverse.harvard.edu/api/access/datafile/4202836 ( from [mit election dataverse)](https://dataverse.harvard.edu/file.xhtml?fileId=4202836&version=8.0)

Interestingly enough I can get the path to load in `smart_open`:

```
from smart_open import open
for line in open("https://dataverse.harvard.edu/api/access/datafile/4202836"):
    print(line)
```

**Comment by andrewcstewart** [comment]
Also, while testing w/ `--log-level info` I never hit line https://github.com/ets/tap-spreadsheets-anywhere/blob/40688b2ddff899940595b2356736775b3afc2d1d/tap_spreadsheets_anywhere/file_utils.py#L174

**Comment by ets** [comment]
Just merged to master with a testcase using your URL.  Should be working now.
