### ISSUE TITLE
Issue discovering local files

### ISSUE THREAD

**Issue by laurentS** [ets/tap-spreadsheets-anywhere#8]
With the following config:
```yaml
      - path: file:///some/absolute/path/that/ends/with/slash/
        pattern: ".*"
```
the tap fails to discover local files in the directory mentioned.
This seems to be because https://github.com/ets/tap-spreadsheets-anywhere/blob/208190734440b57b4445f94e5a0d43a43d20df99/tap_spreadsheets_anywhere/file_utils.py#L199 cuts the path one character too far if a trailing slash is included in the `path` in the config. Replacing that line with:
```python
relpath = os.path.split(abspath)[1]
```
seems to do the trick.

**Comment by ets** [comment]
@laurentS what behavior do you observe if you drop the trailing slash from your config?
```
  - path: file:///some/absolute/path/that/ends/with/slash
        pattern: ".*"
```

**Comment by laurentS** [comment]
I works if I drop the trailing slash. I'd argue for fixing the code though, as it makes the config a little more resilient, especially as there is no error message when the trailing slash is present, so tracing the error is tricky. Happy to send a PR!

**Comment by ets** [comment]
Sure a PR would be great. Certainly no objection to a code change toward more robustness!
